import markdown
from html.parser import HTMLParser

class MarkdownElementExtractor(HTMLParser):
    """
    A custom HTML parser to extract structured elements from HTML generated by the markdown library.
    Modified to output list start/end markers and list item levels.
    """
    def __init__(self):
        super().__init__()
        self.structured_elements = []
        self.current_tag = None
        self.current_text = ""
        self.list_stack = []  # Stack to keep track of 'ol' or 'ul' context
        self.active_emphasis_tags = [] # To handle nested emphasis

    def handle_starttag(self, tag, attrs):
        self.current_tag = tag

        if tag in ['h1', 'h2', 'h3', 'h4', 'h5', 'p']:
            self.current_text = ""
        elif tag == 'ul':
            self.list_stack.append('ul')
            self.structured_elements.append({'type': 'ul_start', 'level': len(self.list_stack) - 1})
        elif tag == 'ol':
            self.list_stack.append('ol')
            self.structured_elements.append({'type': 'ol_start', 'level': len(self.list_stack) - 1})
        elif tag == 'li':
            self.current_text = ""
            # is_ordered is determined by the current list context
            self.is_ordered_list_item = bool(self.list_stack and self.list_stack[-1] == 'ol')
            # Level for the list item itself
            self.current_li_level = len(self.list_stack) -1 if self.list_stack else 0
        elif tag in ['strong', 'em']:
            self.active_emphasis_tags.append(tag)
            self.current_text = "" # Reset for capturing only emphasized text

    def handle_endtag(self, tag):
        text_content = self.current_text.strip()

        if tag in ['h1', 'h2', 'h3', 'h4', 'h5']:
            if text_content:
                self.structured_elements.append({'type': tag, 'text': text_content})
        elif tag == 'p':
            if text_content:
                # Avoid adding paragraphs that are empty or only contained already processed emphasis.
                is_redundant_paragraph = False
                if self.structured_elements:
                    last_el = self.structured_elements[-1]
                    # Check if the last element was emphasis AND this paragraph text is identical
                    # AND this paragraph is not part of a list item (where P tags are common)
                    if last_el['type'] == 'emphasis' and last_el['text'] == text_content:
                         # This heuristic could be improved by checking if the <p> tag was an immediate child of <body> or <li>
                         # For now, this simplification might lead to some desired <p> tags being omitted if they only contain emphasis.
                         # A more robust check would involve knowing the parent of 'p'.
                         # For the current PRD, emphasis creates its own paragraph in docx.
                         pass # Let add_emphasis in DocxWriter handle paragraphs for emphasis.

                # If the paragraph is not solely for an emphasis element that's already captured:
                if not is_redundant_paragraph: # This logic might need refinement.
                    # A simple check: if the last element is emphasis and text matches,
                    # we assume this p-tag was just a wrapper for it.
                    # This avoids double entries when markdown does <p><em>text</em></p>.
                    # However, if emphasis is handled by creating its own paragraph in DocxWriter,
                    # then we should be careful not to add this <p> if it only contained that emphasis.

                    # Revised logic: if the paragraph only contained an emphasis tag,
                    # and that emphasis element was the last thing added, skip this paragraph.
                    if self.structured_elements and \
                       self.structured_elements[-1]['type'] == 'emphasis' and \
                       self.structured_elements[-1]['text'] == text_content and \
                       not self.list_stack: # Only apply this rule if not inside a list
                        pass # Assume emphasis already handled
                    elif text_content: # Add if there's text and it's not a duplicate emphasis wrapper
                        self.structured_elements.append({'type': 'paragraph', 'text': text_content})


        elif tag == 'li':
            if text_content: # Nested tags like <strong> or <em> within <li> might be processed before <li> text.
                self.structured_elements.append({
                    'type': 'list_item',
                    'text': text_content,
                    'ordered': self.is_ordered_list_item,
                    'level': self.current_li_level
                })
            # If an li tag is empty but contains sub-lists, it might be missed.
            # Markdown usually ensures `<li>` has some text or a nested list which itself has text.
            # An empty `<li></li>` would correctly add no text.

        elif tag == 'ul':
            if self.list_stack and self.list_stack[-1] == 'ul': # Ensure matching tag
                level = len(self.list_stack) - 1
                self.list_stack.pop()
                self.structured_elements.append({'type': 'ul_end', 'level': level})
        elif tag == 'ol':
            if self.list_stack and self.list_stack[-1] == 'ol': # Ensure matching tag
                level = len(self.list_stack) - 1
                self.list_stack.pop()
                self.structured_elements.append({'type': 'ol_end', 'level': level})

        elif tag in ['strong', 'em'] and self.active_emphasis_tags:
            active_tag = self.active_emphasis_tags.pop() # Pop the corresponding opening tag
            if text_content:
                style = 'bold' if active_tag == 'strong' else 'italic'
                self.structured_elements.append({'type': 'emphasis', 'text': text_content, 'style': style})

        if tag in ['h1', 'h2', 'h3', 'h4', 'h5', 'p', 'li', 'strong', 'em']:
             self.current_text = "" # Reset text after processing relevant elements
        
        self.current_tag = None


    def handle_data(self, data):
        # Accumulate text if we are inside a relevant tag or active emphasis
        if self.current_tag in ['h1', 'h2', 'h3', 'h4', 'h5', 'p', 'li'] or self.active_emphasis_tags:
            self.current_text += data

    def get_structured_data(self):
        return self.structured_elements


def parse_markdown(markdown_file_path: str) -> list:
    """
    Parses a Markdown file and extracts structured elements,
    including list start/end markers and item levels.
    """
    try:
        with open(markdown_file_path, 'r', encoding='utf-8') as f:
            md_content = f.read()
    except FileNotFoundError:
        return [{"type": "error", "text": f"File not found: {markdown_file_path}"}]
    except Exception as e:
        return [{"type": "error", "text": f"Error reading file {markdown_file_path}: {str(e)}"}]

    # Using 'extra' for features like fenced code, tables, etc.
    # 'sane_lists' helps produce cleaner list HTML, which might aid parsing.
    # 'toc' (Table of Contents extension) could be useful for structure but not directly used yet.
    html_content = markdown.markdown(md_content, extensions=['extra', 'sane_lists', 'toc'])

    parser = MarkdownElementExtractor()
    parser.feed(html_content)
    structured_data = parser.get_structured_data()
    
    # Basic post-processing: Remove paragraphs that are empty AND were not part of a list item
    # This can happen due to multiple newlines in Markdown.
    # final_data = [
    #     elem for elem in structured_data 
    #     if not (elem['type'] == 'paragraph' and not elem['text'].strip())
    # ]
    # This might be too aggressive if empty paragraphs are sometimes intentional.
    # For now, keep all paragraphs and let DocxWriter handle them.

    return structured_data

# End of md_parser.py content
