import markdown
from html.parser import HTMLParser

class MarkdownElementExtractor(HTMLParser):
    """
    A custom HTML parser to extract structured elements from HTML generated by the markdown library.
    Modified to output list start/end markers and list item levels.
    """
    def __init__(self):
        super().__init__()
        self.structured_elements = []
        self.current_tag = None
        self.current_text = ""
        self.list_stack = []  # Stack to keep track of 'ol' or 'ul' context
        self.active_emphasis_tags = []  # To handle nested emphasis
        self.table_data = None  # To store current table data (structured approach)
        self.current_row = None # To store current row data within a table
        self.in_code_block = False # Flag to differentiate between inline code and block code

    def handle_starttag(self, tag, attrs):
        self.current_tag = tag
        attributes = dict(attrs)

        if tag in ['h1', 'h2', 'h3', 'h4', 'h5', 'p', 'blockquote', 'th', 'td']:
            self.current_text = ""
        elif tag == 'ul':
            self.list_stack.append('ul')
            self.structured_elements.append({'type': 'ul_start', 'level': len(self.list_stack) - 1})
        elif tag == 'ol':
            self.list_stack.append('ol')
            self.structured_elements.append({'type': 'ol_start', 'level': len(self.list_stack) - 1})
        elif tag == 'li':
            self.current_text = ""
            # is_ordered is determined by the current list context
            self.is_ordered_list_item = bool(self.list_stack and self.list_stack[-1] == 'ol')
            # Level for the list item itself
            self.current_li_level = len(self.list_stack) -1 if self.list_stack else 0
        elif tag == 'pre':
            self.in_code_block = True
            self.current_text = "" # Reset for capturing code content
            lang = ""
            if 'class' in attributes:
                lang_class = attributes['class']
                if lang_class.startswith('language-'):
                    lang = lang_class.split('language-')[1]
            # Store language temporarily, will be used in handle_endtag for <code>
            self.code_block_language = lang 
        elif tag == 'code':
            # If not inside <pre>, it's inline code.
            # If inside <pre>, text will be captured by <pre>'s handler or directly.
            if not self.in_code_block:
                self.current_text = ""
        elif tag == 'hr':
            self.structured_elements.append({'type': 'horizontal_rule'})
            self.current_text = "" # hr has no content
        elif tag == 'a':
            self.current_href = attributes.get('href', '')
            self.current_text = "" # For link text
        elif tag == 'img':
            src = attributes.get('src', '')
            alt = attributes.get('alt', '')
            self.structured_elements.append({'type': 'image', 'src': src, 'alt': alt})
            self.current_text = "" # img handled, no text content to accumulate for img itself
        elif tag == 'table':
            self.table_data = {'type': 'table', 'headers': [], 'rows': []}
            self.current_text = ""
        elif tag == 'tr':
            self.current_row = [] # Initialize a new row
            self.current_text = ""
        # th, td, blockquote will reset self.current_text as per the first condition in this method.
        elif tag in ['strong', 'em']:
            self.active_emphasis_tags.append(tag)
            self.current_text = "" # Reset for capturing only emphasized text

    def handle_endtag(self, tag):
        text_content = self.current_text.strip()

        if tag in ['h1', 'h2', 'h3', 'h4', 'h5']:
            if text_content:
                self.structured_elements.append({'type': tag, 'text': text_content})
        elif tag == 'p':
            # Revised logic for paragraphs to avoid duplication with emphasis/links if they are sole content
            if text_content:
                # Check if the paragraph solely wraps an element already processed
                # (e.g. <p><a>link</a></p> or <p><em>text</em></p>)
                # This is a heuristic. A more robust way would be to check child elements,
                # but parser doesn't directly expose parent-child relations post-factum easily.
                is_wrapper = False
                if self.structured_elements:
                    last_el = self.structured_elements[-1]
                    if last_el['text'] == text_content and \
                       (last_el['type'] == 'emphasis' or last_el['type'] == 'link' or last_el['type'] == 'inline_code') and \
                       not self.list_stack: # Only apply this rule if not inside a list
                        is_wrapper = True
                
                if not is_wrapper:
                    self.structured_elements.append({'type': 'paragraph', 'text': text_content})

        elif tag == 'li':
            if text_content:
                self.structured_elements.append({
                    'type': 'list_item',
                    'text': text_content,
                    'ordered': self.is_ordered_list_item,
                    'level': self.current_li_level
                })

        elif tag == 'ul':
            if self.list_stack and self.list_stack[-1] == 'ul':
                level = len(self.list_stack) - 1
                self.list_stack.pop()
                self.structured_elements.append({'type': 'ul_end', 'level': level})
        elif tag == 'ol':
            if self.list_stack and self.list_stack[-1] == 'ol':
                level = len(self.list_stack) - 1
                self.list_stack.pop()
                self.structured_elements.append({'type': 'ol_end', 'level': level})
        elif tag == 'strong' or tag == 'em':
            if self.active_emphasis_tags: # Ensure there's an active tag to pop
                active_tag = self.active_emphasis_tags.pop()
                # Ensure the closing tag matches the last opened emphasis tag for correctness,
                # though HTMLParser usually handles mismatched tags by closing them implicitly.
                if active_tag == tag and text_content:
                    style = 'bold' if active_tag == 'strong' else 'italic'
                    self.structured_elements.append({'type': 'emphasis', 'text': text_content, 'style': style})
        elif tag == 'pre':
            # Code content is actually inside the 'code' tag within 'pre'
            # This will be handled by 'code' tag's endtag logic when self.in_code_block is true
            self.in_code_block = False 
            self.code_block_language = None # Reset language
        elif tag == 'code':
            if self.in_code_block: # This 'code' tag is part of a 'pre' block
                lang = getattr(self, 'code_block_language', '') # Get language stored from <pre>
                self.structured_elements.append({'type': 'code_block', 'text': text_content, 'language': lang})
            else: # Inline code
                if text_content:
                    self.structured_elements.append({'type': 'inline_code', 'text': text_content})
        elif tag == 'blockquote':
            if text_content:
                self.structured_elements.append({'type': 'blockquote', 'text': text_content})
        elif tag == 'a':
            if text_content or self.current_href: # Add link if there's text or an href
                self.structured_elements.append({'type': 'link', 'text': text_content, 'href': self.current_href})
            self.current_href = None
        elif tag == 'table':
            if self.table_data:
                self.structured_elements.append(self.table_data)
            self.table_data = None
        elif tag == 'tr':
            if self.table_data is not None and self.current_row is not None:
                # Determine if this row should be in headers or rows based on content
                is_header_row = all(cell.get('is_header') for cell in self.current_row)
                if is_header_row and not self.table_data['headers']: # Add to headers if empty and cells are th
                     self.table_data['headers'].append(self.current_row)
                else: # Otherwise, add to data rows
                    # If it was parsed as a header row but headers are already populated, make it a data row
                    # This handles cases like <thead><tr><th>...</th></tr></thead><tbody><tr><th>... (mistake)
                    # For simplicity, we are not strictly parsing thead/tbody, but inferring from th/td content of rows.
                    # A more robust parser might use thead/tbody explicitly.
                    if is_header_row and self.table_data['headers']:
                         for cell in self.current_row: cell['is_header'] = False
                    self.table_data['rows'].append(self.current_row)
            self.current_row = None
        elif tag == 'th':
            if self.current_row is not None and text_content:
                self.current_row.append({'text': text_content, 'is_header': True})
        elif tag == 'td':
            if self.current_row is not None and text_content:
                self.current_row.append({'text': text_content, 'is_header': False})
        # hr, img are handled in starttag as they don't have end tags in the same way or content.

        if tag in ['h1', 'h2', 'h3', 'h4', 'h5', 'p', 'li', 'strong', 'em', 'pre', 'code', 'blockquote', 'a', 'th', 'td']:
             self.current_text = "" # Reset text after processing relevant elements
        
        self.current_tag = None


    def handle_data(self, data):
        # Accumulate text if we are inside a relevant tag or active emphasis
        # Added 'blockquote', 'th', 'td', 'a'. For 'code', depends on context (in_code_block or not)
        if self.current_tag in ['h1', 'h2', 'h3', 'h4', 'h5', 'p', 'li', 'blockquote', 'th', 'td', 'a'] \
           or self.active_emphasis_tags \
           or (self.current_tag == 'code' and not self.in_code_block) \
           or (self.in_code_block and self.current_tag == 'code'): # Capture text for code inside pre
            self.current_text += data

    def get_structured_data(self):
        return self.structured_elements


def parse_markdown(markdown_file_path: str) -> list:
    """
    Parses a Markdown file and extracts structured elements,
    including list start/end markers and item levels.
    """
    try:
        with open(markdown_file_path, 'r', encoding='utf-8') as f:
            md_content = f.read()
    except FileNotFoundError:
        return [{"type": "error", "text": f"File not found: {markdown_file_path}"}]
    except Exception as e:
        return [{"type": "error", "text": f"Error reading file {markdown_file_path}: {str(e)}"}]

    # Using 'extra' for features like fenced code, tables, etc.
    # 'sane_lists' helps produce cleaner list HTML, which might aid parsing.
    # 'toc' (Table of Contents extension) could be useful for structure but not directly used yet.
    html_content = markdown.markdown(md_content, extensions=['extra', 'sane_lists', 'toc'])

    parser = MarkdownElementExtractor()
    parser.feed(html_content)
    structured_data = parser.get_structured_data()
    
    # Basic post-processing: Remove paragraphs that are empty AND were not part of a list item
    # This can happen due to multiple newlines in Markdown.
    # final_data = [
    #     elem for elem in structured_data 
    #     if not (elem['type'] == 'paragraph' and not elem['text'].strip())
    # ]
    # This might be too aggressive if empty paragraphs are sometimes intentional.
    # For now, keep all paragraphs and let DocxWriter handle them.

    # Post-processing to refine table structure:
    # If a table has multiple lists in 'headers', it means multiple <tr> in <thead>
    # We'll keep it as a list of header rows.
    # Same for 'rows' if there are multiple <tr> in <tbody>
    
    # Example of further refinement if needed (e.g. ensuring cells are uniform per row, etc.)
    # For now, the structure is a list of header rows, and a list of data rows.
    # Each row is a list of cell dictionaries.

    return structured_data

# End of md_parser.py content
